namespace BetterWinUI.DependencyInjection.PageActivation;

/// <summary>
/// Specifies how generated page activation handles pages that are absent from the service provider.
/// </summary>
public enum UnregisteredPageBehavior
{
    /// <summary>
    /// Throws an <see cref="InvalidOperationException"/> describing the missing page registration.
    /// </summary>
    Throw = 0,

    /// <summary>
    /// Falls back to the activator generated by the WinUI XAML compiler.
    /// </summary>
    FallbackToXamlActivator = 1
}