using Microsoft.CodeAnalysis;

namespace BetterWinUI.PageActivation.Generators.Internal;

/// <summary>Defines application declaration rules shared by the activation generators.</summary>
internal static class PageActivationApplication
{
    /// <summary>Checks the application shape supported by generated partial declarations.</summary>
    public static bool IsSupported(INamedTypeSymbol symbol, INamedTypeSymbol? applicationType)
    {
        if (applicationType is null || symbol.TypeKind != TypeKind.Class || symbol.IsAbstract ||
            symbol.Arity != 0 || symbol.ContainingType is not null || symbol.ContainingNamespace.IsGlobalNamespace)
            return false;

        for (var current = symbol.BaseType; current is not null; current = current.BaseType)
            if (SymbolEqualityComparer.Default.Equals(current, applicationType))
                return true;
        return false;
    }

    /// <summary>Checks whether user code conflicts with the generated by-value overload.</summary>
    public static bool HasActivationConflict(INamedTypeSymbol symbol, ITypeSymbol? parameterType)
    {
        return symbol.GetMembers("UsePageActivation").Any(member =>
            !member.Locations.Any(static location => location.SourceTree?.FilePath.EndsWith(
                ".PageActivation.g.cs", StringComparison.OrdinalIgnoreCase) == true) &&
            (member is not IMethodSymbol method ||
             (method is { Arity: 0, Parameters: [{ RefKind: RefKind.None }] } &&
              SymbolEqualityComparer.Default.Equals(method.Parameters[0].Type, parameterType))));
    }
}