<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <IsAotCompatible>false</IsAotCompatible>
        <IsPackable>false</IsPackable>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <RootNamespace>BetterWinUI.DependencyInjection.PageActivation.Generator</RootNamespace>
        <PackageScribanIncludeSource>true</PackageScribanIncludeSource>
        <PolySharpIncludeRuntimeSupportedAttributes>true</PolySharpIncludeRuntimeSupportedAttributes>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.CSharp" PrivateAssets="all"/>
        <PackageReference Include="PolySharp" PrivateAssets="all"/>
        <PackageReference Include="Scriban" IncludeAssets="build" PrivateAssets="all"/>
        <PackageReference Include="System.Threading.Tasks.Extensions" PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Templates\*.scriban"/>
    </ItemGroup>
</Project>
